    ############################## 
     # Country definition for CZE # 
     ############################## 
  
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = CZE 
    puppet                 = AUS
    control                = AUS
	ai_settings = { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes } }
   # Resource Reserves 
	energy                 = 2160
	metal                  = 1080
	rare_materials         = 540
	supplies               = 500
	oil                    = 500 
	money                  = 20 
	manpower               = 10 
	capital                = 207 
	
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 8 
     political_left    = 3 
     free_market       = 9 
     freedom           = 8 
     professional_army = 5 
     defense_lobby     = 9 
     interventionism   = 5 
    } 	
	
	
   diplomacy = 
   {  relation = {  tag = ENG value = -125  } 
     relation = {  tag = FRA value = -50  } 
     relation = {  tag = GER value = 150  } 
     relation = {  tag = HUN value = -50  } 
     relation = {  tag = AUS value = 200 access = yes  } 
     relation = {  tag = POL value = -40  } 
     relation = {  tag = SOV value = -200  } 
    } 
   SpyInfo                = {  country = "CZE" NumberOfSpies = 2  } 
   nationalprovinces      = {  196 197 198 199 200 201 202 203 204 205 206 207 } 
   ownedprovinces         = {  196 197 198 199 200 201 202 203 204 205 206 207 } 
   controlledprovinces    = {  196 197 198 199 200 201 202 203 204 205 206 207 } 

   # Germany 1936 techs 
  ####################### 
  techapps = { 
  #Early Infantry Division  
  1010 1020 1030 1040 1050 1060 1070 1080 1090
  #SEMI-MOTORIZED CAVALRY 
  13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 
  # Motorized Infantry
  1396
  #Early Mountain Division 
  1160  1170 1180 1190 1200 1210 1220 1230 1240
  #Engineers
  1830 1840 1850 1860
  #Interbellum 1930 Supply
  1910 1920 1930 1940 1950 1960 1970 1980

  #Basic Armoured Car  
  2860 2870 2880 2020 2150
  #Early Tank 
  7600 7610 2620 2010 2630 2640 2646 2650 2030
  #Early Field Artillery 
  2290 2300 2310 2900 2910 2920 2930
  #Early Static Anti-Air Artillery 
  2800 2450 21180 21190 21200
  #Basic Anti-Air Artillery Brigade 
  2810 2820 2510

  #Improved Destroyer 
  3010 3020 3030 3040 3050 3060
  #Basic Light Cruiser 
  3110 3120 3130 3140 3150 3160
  #Improved Heavy Cruiser 
  3210 3220 3230 3240 3250 3260  
  #Early Battlecruiser
  3310 3320 3330 3340
  #Early Battleship 
  3410 3420 3430 3440 3450 3456 3460 3470
  #Improved Submarine 
  3610 3620 3630 3640 3650
  #Great War Air Carrier 
  3510
  #CAG
  4900
  #Improved Light carrier 
  12100 12110
  #Torpedo & ASW 18
  3720 3730 3736 3740 3750 3900
  #Troopships
  3810 3820

  #Basic Air Transport 
  4290 4250
  #Multirole fighter
  4300 4310 4320 4330 4340
  #CAS
  4400
  #ww1 strategic bomber
  4800 4810 4820
  #ww1 navalbomber
  4700 4710
  #Early Fighter  
  4500 4510 4520 4530 4540 4550 4010 4020
  #Early Bomber
  4600 4610 4620 4630 4120 4130
  #SEAPLANES
  4740 4750 4760

  #Manufacturing
  5810 5820 5050 5830 5060
  #Improved Construction Engineering 
  5800 5080 5090
  #Basic Oil Refining
  5190 5200
  #Computers & cryptografi
  5310 54010 54020 54030 5316 5326
  #Exp. Rocket
  5560
  #Mechanized Agriculture 
  5700 5710 5010 5020
  #Medicine
  5600 5610 5620 5630

  # Great War Land Doctrines (central powers)
  6500 6510 6530 6550 6590 6600 6620 6650 6670 6610 6680 6690 6700 6710 6910
  # WW2 Land Doctrines
  6210 6220 6230 6250 6900
  #Great War Hospital System 
  14000 14010 14020

  #Air Doctrines - ww2 techs
  27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9090

  #Naval Doctrines
  8010 8020 8030 8040 8050 8060 8070 8080
  # Amphib
  82300
  # Naval Logistics
  82500
  # Naval Interdiction
  8500 8510 8520 8550 8560 8570
  # Trade Interdiction Submarine
  8600 8610
  # Indirect Approach
  81300 81310 81320 81330 81340 81350
  # Naval Supremacy
  8100 8110 8120 8150 8160 8170 8200 8210
} 
inventions = { 3000027 }

   headofstate            = {  type = 9 id = 115001  } 
   headofgovernment       = {  type = 9 id = 115002  } 
   foreignminister        = {  type = 9 id = 120003  } 
   armamentminister       = {  type = 9 id = 120004  } 
   ministerofsecurity     = {  type = 9 id = 120005  } 
   ministerofintelligence = {  type = 9 id = 120006  } 
   chiefofstaff           = {  type = 9 id = 120007  } 
   chiefofarmy            = {  type = 9 id = 120008  } 
   chiefofnavy            = {  type = 9 id = 120009  } 
   chiefofair             = {  type = 9 id = 120010  } 
   # ################################ 
   # Czech army 
   # ################################ 
   landunit = 
   {  id       = {  type = 23000 id = 1  } 
     location = 207 
     name     = "Královská armáda" 
     Division = 
     {  id       = {  type = 26000 id = 2  } 
       name     = "1. Horská Brigada" 
       type     = bergsjaeger
       strength  = 30 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 26000 id = 3  } 
       name     = "2. Horská Brigada" 
       type     = bergsjaeger
       strength  = 30 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 26000 id = 4  } 
       name     = "13. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
     Division = 
     {  id       = {  type = 26000 id = 5  } 
       name     = "15. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
     Division = 
     {  id       = {  type = 26000 id = 6  } 
       name     = "18. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
     Division = 
     {  id       = {  type = 26000 id = 7  } 
       name     = "21. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
     Division = 
     {  id       = {  type = 26000 id = 8  } 
       name     = "22. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
    } 

   landunit = 
   {  id       = {  type = 26000 id = 9  } 
     location = 196 
     name     = "I. Armáda" 
     Division = 
     {  id       = {  type = 26000 id = 10  } 
       name     = "1. Rychlá Brigada" 
       type     = cavalry 
       model    = 9 
       strength  = 40
       extra = light_armor_brigade
       brigade_model = 4 
      } 
     Division = 
     {  id       = {  type = 26000 id = 11  } 
       name     = "2. Divize" 
       type     = infantry 
       strength  = 80 
       model    = 7 
       extra    = artillery 
	   brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 26000 id = 12  } 
       name     = "1. Divize" 
       type     = garrison
       strength  = 80 
       model    = 4 
      } 
     Division = 
     {  id    = {  type = 26000 id = 13  } 
       name  = "3. Divize" 
       type  = infantry 
       model = 7
	strength = 80
      } 
     Division = 
     {  id       = {  type = 26000 id = 14  } 
       name     = "4. Divize" 
       type     = infantry 
       strength  = 80 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 26000 id = 15  } 
       name     = "5. Divize" 
       type     = infantry 
       strength  = 80 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 26000 id = 16  } 
       name     = "16. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
     Division = 
     {  id       = {  type = 26000 id = 17  } 
       name     = "17. Divize" 
       type     = infantry 
       strength  = 5 
       model    = 6 
      } 
    } 

   landunit = 
   {  id       = {  type = 26000 id = 22  } 
     location = 199 
     name     = "II. Armáda" 
     Division = 
     {  id       = {  type = 26000 id = 23  } 
       name     = "7. Divize" 
       type     = infantry 
       strength  = 80 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 26000 id = 24  } 
       name     = "8. Divize" 
       type     = infantry 
       strength  = 80 
       model    = 7 
      } 
     Division = 
     {  id       = {  type = 26000 id = 25  } 
       name     = "6. Divize" 
       type     = infantry 
       strength  = 80 
       model    = 7 
       extra    = artillery 
	   brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 26000 id = 26  } 
       name     = "2. Rychlá Brigada" 
       type     = cavalry 
       model    = 9 
       strength  = 40
       extra = light_armor_brigade
       brigade_model = 4 
      } 
    } 


  } 
 