 
 ############################## 
 # Country definition for CHC # 
 ############################## 
  

  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = CHC
	ai_settings = { flags = { MOB1 = yes MOB2 = yes RES = yes } } 
	intrinsic_gov_type     = leninist 
	extra_tc               = 7 
	capital                = 1369 # Guangzhou 
	# Resource Reserves 
	energy                 = 240
	metal                  = 120
	rare_materials         = 60
	oil                    = 100 
	supplies               = 800 
	money                  = 50 
	manpower               = 220 #120 added to reinforce units 
	dissent                = 5 
   diplomacy = 
   {  relation = {  tag = JAP value = -200  } 
     relation = {  tag = MAN value = -100  } 
     relation = {  tag = CHI value = -200  } 
     relation = {  tag = CGX value = -200  } 
     relation = {  tag = CYN value = -200  } 
     # CHC protected by Shaanxi provincial governor who was secret communist
     relation = {  tag = CSX value = -75  } 
     relation = {  tag = CXB value = -100  } 
     relation = {  tag = SOV value = 100  } 
     relation = {  tag = MON value = 25  }
     relation = {  tag = U67 value = 50  } 
     relation = {  tag = SIK value = 40  }
    } 
   SpyInfo                = {  country = "CHC" NumberOfSpies = 3  } 
   nationalprovinces      = {   
  
 #Communist China at start      
 1255 1259 1260
  
 #Nationalist China  
 1256 1257 1258 1261 1262 1267 1291 1292 1293 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322 1323 1324 1325 1326 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350  1352 1353 1354 1355 1356 1357 1358 1359 1360      
  
 #Yunnan          
 1384 1385 1386 1387 1388 1389 1390 
  
 #Guanxi Clique  
 1361 1365 1367 1368 1369 1370 1373 1374 1375 1376 1377 1378 1379 1380 1381 1382 1383  
  
 #Shanxi       
 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252 1253 1254 1327 1328 1329 1330 1331 1332   
  
 #Manchoukou 
 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1220 1235 1236 1237
  
 #Xibei san ma            
 1263 1264 1265 1266 1268 1269 1270 1271 1272 1283 1284 1285   
  
 #Tibet       
 1286 1287 1288 1289 1290 1294 1295 
  
 #Sinkiang        
 1273 1274 1275 1277 1279 1280 1281 1282 
  
 #India        
 1276 1278  
  
 #Japan In China     
 1219 1238 1239 1240 
  
 #European Possessions     
  1371 1372  
   
 #Taiwan     
  1362 1363 1364  
  
                             } 
	ownedprovinces         = { 1374 1379 1377 1373 1369 1383 1380 1368 1354 1375 1311 1378 1370 1375 1354 1356 1349 1355 1308 1309 1312 1310 1308 1318 1313 1353 1352 1350 1359 1357 1360 1358 1347 1346 1348 1345 1342 1351  } 
	controlledprovinces    = { 1374 1379 1377 1373 1369 1383 1380 1368 1354 1375 1311 1378 1370 1375 1354 1356 1349 1355 1308 1309 1312 1310 1308 1318 1313 1353 1352 1350 1359 1357 1360 1358 1347 1346 1348 1345 1342 1351  }
	claimedprovinces = { 
	1455 1458 #Arunachal Pradesh
						} 
	#Communist China
 	techapps = { 

	# Construction Engineering - Up to 1910
	5800 5080
	
	# Computers
	5310

	# Crypto
	5316 5326 5327

	# Infantry Division
	1010 1020 1030 1040 1050 1060 1070 1080
	# Mountain Division
	1160 1170 1180 1190 1200 1210 1220 1230 
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330

	# Supply 
	1910 1920 1930 1940 1950 1960

	# Field Artillery 
	2290 2300 2310 2900 2910

	# Hospital System
	14000 14010 14020
	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
	# Manpower Doctrine
	6570 6300


	} 

blueprints = {
	
	# Manufacturing
	5810 5820

	#Computers
	54010

	# Cavalry
	1340 1350 1360 1370

	# Armoured Car  
	2860

	#Medicine
	5600

	# Interceptor Fighter  
	4500 4510 4520  
	# Multirole Fighter
	4300 4310
	# Tactical Bomber 
	4600 4610 4620
	# Strategic Bomber
	4800


}
inventions = { 3000027 }

   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 4 
     political_left    = 9 
     free_market       = 4 
     freedom           = 7 
     professional_army = 5 
     defense_lobby     = 10 
     interventionism   = 5 
    } 
   headofstate            = {  type = 9 id = 260898  } 
   headofgovernment       = {  type = 9 id = 260904  } 
   foreignminister        = {  type = 9 id = 260861  } 
   armamentminister       = {  type = 9 id = 260902  } 
   ministerofsecurity     = {  type = 9 id = 260850  } 
   ministerofintelligence = {  type = 9 id = 260909  } 
   chiefofstaff           = {  type = 9 id = 260820  } 
   chiefofarmy            = {  type = 9 id = 260867  } 
   chiefofnavy            = {  type = 9 id = 260806  } 
   chiefofair             = {  type = 9 id = 260808  } 
   # ###### 
   # COMMUNIST CHINA 1936 OOB
   # http://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E5%B7%A5%E5%86%9C%E7%BA%A2%E5%86%9B%E6%88%98%E6%96%97%E5%BA%8F%E5%88%97
   ####################
	# Guangzhou Force #
	####################
	landunit = 
   {  location = 1369 # Guangzhou
     name     = "Chinese National Revolutionary Army" 
     id       = {  type = 22055 id = 1001  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1002 } 
       name       = "CNRA Headquarters" 
       type       = hq
	   strength  = 100
       model     = 2
	  extra1 = police
	   brigade_model1 = 1
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1003  } 
       name       = "1st Division" 
       type       = infantry
	   strength  = 100
       model     = 8
	  
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1004  } 
       name       = "2nd Division" 
       type       = infantry
	   strength  = 100
       model     = 6
	  
      }
    }
	landunit = 
   {  location = 1369 # Guangzhou
     name     = "Guangzhou National Revolutionary Army" 
     id       = {  type = 22055 id = 1005  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1006 } 
       name       = "3rd Division" 
       type       = infantry
	   strength  = 100
       model     = 8
	   extra1 = artillery
	   brigade_model1 = 4
	  
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1007  } 
       name       = "4th Division" 
       type       = infantry
	   strength  = 100
       model     = 7
	   extra1 = artillery
	   brigade_model1 = 4
	   
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1008  } 
       name       = "5th division" 
       type       = infantry
	   strength  = 100
       model     = 7
	   
      }
	  Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1009  } 
       name       = "Guangzhou NRA Reserves" 
       type       = infantry
	   strength  = 50
       model     = 5
	   
      }
	 }
	landunit = 
   {  location = 1369 # Guangzhou
     name     = "Guangzhou Red Army" 
     id       = {  type = 22055 id = 1010  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1011 } 
       name       = "1st Guangzhou Red Guards" 
       type       = militia
	   strength  = 100
       model     = 4
	   
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1012  } 
       name       = "2nd Guangzhou Red Guards" 
       type       = militia
	   strength  = 100
       model     = 4
	   
      }
	 
    }
	landunit = 
   {  location = 1369 # Guangzhou
     name     = "Soviet Military Mission" 
     id       = {  type = 22055 id = 1013  } 
     Division = 
     {  experience = 30
       id         = {  type = 22055 id = 1014 } 
       name       = "1-ya Kitayskaya Motostrelkovaya Diviziya" 
       type       = motorized
	   strength  = 100
       model     = 0
	   extra1 = light_armor_brigade 
       brigade_model1     = 3
	   
      }
	  Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1015 } 
       name       = "2-ya Kitayskaya Motostrelkovaya Diviziya" 
       type       = motorized
	   strength  = 100
	   model = 0
	   extra1 = light_armor_brigade 
       brigade_model1     = 3
      }

    }
######################
	# Changsha Task Force #
	######################
	landunit = 
   {  location = 1308 # Changsha
     name     = "Changsha National Revolutionary Army" 
     id       = {  type = 22055 id = 1016  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1017 } 
       name       = "6th Division" 
       type       = infantry
	   strength  = 100
       model     = 6
	   extra1 = artillery 
       brigade_model1     = 5
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1018 } 
       name       = "7th Division" 
       type       = infantry
	   strength  = 95
       model     = 6
	   extra1 = armored_car 
       brigade_model1     = 2
	   
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1019  } 
       name       = "8th Division" 
       type       = infantry
	   strength  = 70
       model     = 5
	   
      }
	  Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1020 } 
       name       = "9th Division" 
       type       = infantry
	   strength  = 50
       model     = 5
	   
      }
	  Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1021  } 
       name       = "Changsha CNRA Reserves" 
       type       = infantry
	   strength  = 50
       model     = 5
	   
      }
    }
	landunit = 
   {  location = 1308 # Changsha
     name     = "CNRA Cavalry Corps" 
     id       = {  type = 22055 id = 1022  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1023 } 
       name       = "1st 1st Cavalry Division" 
       type       = cavalry
	   strength  = 100
       model     = 6
	   extra1 = engineer 
       brigade_model1     = 1
	   
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1024 } 
       name       = "2nd Cavalry Division" 
       type       = cavalry
	   strength  = 100
       model     = 6
	   
      }
	  Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1025 } 
       name       = "3rd Cavalry Division" 
       type       = cavalry
	   strength  = 75
       model     = 5
	   
      }
    }
	
	######################
	# Chengde Task Force #
	######################
	
	landunit = 
   {  location = 1310 # Chengde
     name     = "Chengde Red Army" 
     id       = {  type = 22055 id = 1026  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1027 } 
       name       = "1st Chengde Red Guards" 
       type       = militia
	   strength  = 100
       model     = 4
	   
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1028  } 
       name       = "2nd Chengde Red Guards" 
       type       = militia
	   strength  = 100
       model     = 4
	   
      }
	  Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1029  } 
       name       = "3rd Chengde Red Guards" 
       type       = militia
	   strength  = 50
       model     = 4
	   
      }
	 
    }
	
	######################
	# Hangzhou Task Force #
	######################
	landunit = 
   {  location = 1345 # Hangzhou
     name     = "Hangzhou National Revolutionary Army" 
     id       = {  type = 22055 id = 1030  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1031 } 
       name       = "10th Division" 
       type       = infantry
	   strength  = 100
       model     = 6
	   extra1 = artillery 
       brigade_model1     = 5
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1032 } 
       name       = "11th Division" 
       type       = infantry
	   strength  = 95
       model     = 6
	   extra1 = artillery 
       brigade_model1     = 3
	   
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1033  } 
       name       = "12th Division" 
       type       = infantry
	   strength  = 90
       model     = 6
	   extra1 = cavalry_brigade 
       brigade_model1     = 3
      }
    }
	######################
	# Southwestern Task Force #
	######################
	landunit = 
   {  location = 1300 # Yibin
     name     = "Southwestern Border Force" 
     id       = {  type = 22055 id = 1034  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1035 } 
       name       = "13th Division" 
       type       = infantry
	   strength  = 100
       model     = 4
	   extra1 = artillery 
       brigade_model1     = 5
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1036 } 
       name       = "Yibin Red Guards" 
       type       = militia
	   strength  = 100
       model     = 3
	   
      }
	 }
	######################
	# Southern Task Force #
	######################
	landunit = 
   {  location = 1374 # 
     name     = "Southern Border Force" 
     id       = {  type = 22055 id = 1037  } 
     Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1038 } 
       name       = "14th Division" 
       type       = infantry
	   strength  = 80
       model     = 4
	   extra1 = artillery 
       brigade_model1     = 5
      }
	 Division = 
     {  experience = 30 
       id         = {  type = 22055 id = 1039 } 
       name       = "Viet Nam Quoc Dan Dang" 
       type       = militia
	   strength  = 100
       model     = 2
	   
      }
	 }
	################
	# Airforce OOB #
	###############
	# Hunan
	airunit = 
   {  location = 1312 # Hengyang
     name     = "Hunan Air Force" 
     base     = 1312 # Hengyang
     id       = {  type = 22055 id = 1040  } 
     Division = 
     {  id           = {  type = 22055 id = 1041  } 
       name         = "11th 13th 14th Squadron" 
       type         = tactical_bomber
       model        = 3
       strength     = 25
      } 
	  Division = 
     {  id           = {  type = 22055 id = 1042  } 
       name         = "12th Squadron" 
       type         = interceptor 
       model        = 1
       strength     = 35 
      } 
    }
	airunit = 
   {  location = 1312 # Hengyang
     name     = "Soviet Air Volunteers" 
     base     = 1312 # Hengyang
     id       = {  type = 22055 id = 1043  } 
     Division = 
     {  id           = {  type = 22055 id = 1044  } 
       name         = "1. KIABR" 
       type         = interceptor
       model        = 6
       strength     = 50
      } 
    }
	###navy####
	navalunit = 
   {  location = 1369 # Guangzhou 
     name     = "RoC Naval Academy Fleet" 
     id       = {  type = 22055 id = 1045  } 
     base     = 1328
	   Division = 
     {  id           = {  type = 22055 id = 1046  } 
       name  = "1st Destroyer Flotilla" 
       type  = destroyer
	   strength = 100
       model = 1  #Gunboat
	   experience = 20
      }
	  Division = 
     {  id           = {  type = 22055 id = 1047  } 
       name  = "2nd Destroyer Flotilla" 
       type  = destroyer
	   strength = 80
       model = 1  #Gunboat
	   experience = 20
      }
	 Division = 
     {  id           = {  type = 22055 id = 1048  } 
       name  = "3rd Destroyer Flotilla" 
       type  = destroyer
	   strength = 80
       model = 1  #Gunboat
	   experience = 20
      }
     Division = 
     {  id    = {  type = 22055 id = 1049 } 
       name  = "1st Transport Flotilla"
       type  = transport
	   strength = 60
       model = 0  
      } 
	  Division = 
     {  id           = {  type = 22055 id = 1050  } 
       name  = "Sun Yat-Sen" 
       type  = light_cruiser
	   strength = 100
       model = 1  #Gunboat
	   experience = 20
      }
	}
  } 
 
 