 
 ############################## 
 # Country definition for FRA # 
 ############################## 
 
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = FRA
	ai_settings	= { flags = { FRABuildStandard = yes MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes } } 
	capital                = 55 
	# Resource Reserves 
	energy                 = 7440
	metal                  = 3720
	rare_materials         = 1860
	oil                    = 500 
	supplies               = 500 
	money                  = 50 
	manpower               = 28 
	transports             = 570 
	escorts                = 60
	dissent = 10

   diplomacy = 
   {  relation = {  tag = AST value = 150  } 
     relation = {  tag = AUS value = -10  } 
     relation = 
     {  tag        = BEL 
       value      = 120 
       guaranteed = {  day = 0 month = january year = 1935  } 
      } 
     relation = {  tag = BHU value = 150  } 
     relation = {  tag = BUL value = 20  } 
     relation = {  tag = CAN value = 150  } 
     relation = {  tag = CZE value = 150  } 
     relation = {  tag = ENG value = 150  } 
     relation = {  tag = EST value = 65  } 
     relation = {  tag = ETH value = 25  } 
     relation = {  tag = FIN value = 85  } 
     relation = {  tag = GER value = -35  } 
     relation = {  tag = GRE value = 20  } 
     relation = 
     {  tag        = HOL 
       value      = 75 
       guaranteed = {  day = 0 month = january year = 1935  } 
      } 
     relation = {  tag = HUN value = -70  } 
     relation = {  tag = IRE value = 25  } 
     relation = {  tag = IRQ value = 100  } 
     relation = {  tag = ITA value = -50  } 
     relation = {  tag = JAP value = -20  } 
     relation = {  tag = LAT value = 65  } 
     relation = {  tag = LIT value = 65  } 
     relation = 
     {  tag        = LUX 
       value      = 120 
       guaranteed = {  day = 0 month = january year = 1935  } 
      } 
     relation = {  tag = NEP value = 150  } 
     relation = 
     {  tag        = NOR 
       guaranteed = {  day = 0 month = january year = 1933  } 
      } 
     relation = {  tag = NZL value = 150  } 
     relation = {  tag = OMN value = 150  } 
     relation = 
     {  tag        = POL 
       value      = 100 
       guaranteed = {  day = 0 month = january year = 1933  } 
      } 
     relation = {  tag = ROM value = 50  } 
     relation = {  tag = SAF value = 150  } 
     relation = {  tag = SAU value = 10  } 
     relation = 
     {  tag        = SCH 
       value      = 1 
       guaranteed = {  day = 0 month = january year = 1935  } 
      } 
     relation = {  tag = SIA value = -100  } 
     relation = {  tag = SOV value = 100  } 
     relation = {  tag = SPR value = 10  } 
     relation = 
     {  tag        = TUR 
       value      = 50 
       guaranteed = {  day = 0 month = january year = 1935  } 
      } 
     relation = {  tag = U03 value = 50 access = yes  }  
     relation = {  tag = U04 value = 50 access = yes  }  
     relation = {  tag = USA value = 65  } 
     relation = {  tag = YEM value = 150  } 
     relation = 
     {  tag        = YUG 
       value      = 50 
       guaranteed = {  day = 0 month = january year = 1935  } 
      } 
    } 
   SpyInfo                = {  country = "FRA" NumberOfSpies = 9  } 



   # Togoland 
   # Metropolitan France  
   nationalprovinces      = { 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 106 
          
                             } 
   # Metropolitan France 
   ownedprovinces         = {  37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 95 96 97 98 99 100 101 102 103 106 727 728 729 730 731 732 733 734 735 736 737 738 739 743 921 922 942 943 944 945 946 947 957 958 959 960 961 962 965 966 967 968 970 971 972 973 974 975 976 977 978 980 981 982 983 984 985 986 2135 
                             } 
   # Togoland 
   # Metropolitan France 
   controlledprovinces    = {  37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 95 96 97 98 99 100 101 102 103 106 727 728 729 730 731 732 733 734 735 736 737 738 739 743 921 922 942 943 944 945 946 947 957 958 959 960 961 962 965 966 967 968 970 971 972 973 974 975 976 977 978 980 981 982 983 984 985 986  2135 
                             }
	claimedprovinces = {
                            727 728 729 730 731 732 733 734 735 736 737 738 739 743 #Algeria
                            740 741 742 744 745 746 747 748 749 # Tunisia
                            907 908 909 910 911 914 915 917 918 919 #French Congo and Cameroon
                            920 921 922 923 924 925 926 927 928 #Central Africa
                            942 943 944 945 946 947 #Niger
                            948 949 950 951 #Slave Coast
                            957 958 959 #Volta
                            960 961 962 #Ivory Coast
                            965 966 967 968 970 #Guinean Coast
                            971 972 973 974 975 976 977 #Malian Valleys
                            978 980 #Senegambia
                            981 982 983 #Mauretania
                            984 985 986 #Malian Desert
                            833 #Djbouti
                            1001 1002 1003 996 999 1000 #Madagascar + nearby Island
                            
                            2000  #Cayenne 
                            1752 1767 1768 #French West Indies
                            1581 1582 1583 1584 1585 1586 1730 1740 1743 1744 #French Pacific Island
                            2135 #Saint Pierre island near Newfoundland
						}		 
		 
   # FRA 1936 techs 
   # ###################### 
   techapps               = { 
#Basic Armoured Car  
2860 2870 2880 2020 2150
#Early Tank 
7600 7610 2620 2010 2630 2640 2646 2650 
#Great War Heavy Field Artillery 
2290 2300 2310 2900
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Early Anti-Tank Artillery 
##2400
#Early Infantry Division  
1010  1020 1030 1040 1050 1060 1070 1080 1090
#1930 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Motorised Inf
1396
#Naval Infantry
1560
#Engineers
1830 1840 1850 1860
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#Modern Agriculture 
5700 5710 5010
#Basic Machine Tools 
5810 5820 5050 5830 5060
#Improved Construction Engineering 
5800 5080 5090 
#improved Oil Refining #5190

#Computers 
5310 54010 54020 54030
#cryptografi
5316 5326
#Faculty of Atomic Research 
5470 5480
#Medicine
5600 5610 5620 5630
#Exp. Rocket
5560

#Improved Destroyer 
3010 3020 3030 3040 3050 3060 
#Basic Light Cruiser 
3110 3120 3130 3140 3150 3160
#Improved Heavy Cruiser 
3210 3220 3230 3240 3250 3260 
#Early Battleship 
3410 3420 3430 3440 3450 3456 3460 3470
#Great War Air Carrier 
3510
#Improved Light carrier 
12100 12110 12120
#Short Range Submarine 
3610 3620 3630 3640
# Battle Cruiser
3310 3320 3330 3340
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810 3820

#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Early Bomber 
4600 4610 4620 4630 4120 4130
#Multirole fighter
4300 4310 4320 4330
#SEAPLANES
4740 4750 4760 4770
#ww1 strategic bomber
4800 4810 4820
#ww1 navalbomber
4700 4710
#CAG 30
4900 4910
#Great War Hospital System 
14000 14010 14020

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
#Land Doctrines
6560 6030

#Naval Doctrines
# Theories
8010 8020 8030 8040 8050 8060 8070 8080 
# Amphibious Warfare
82300
# Naval Logistics
82500
# Naval Interdiction
8500 8510 8550 8600 
# Engagement Tactic (Fleet-in-Being)
8900 8910 8920 8930 8940
# Naval Supremacy
8100 8110 8120 8150 8160 8200 8210

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040

} 
inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 6 
     free_market       = 8 
     freedom           = 9
     professional_army = 5 
     defense_lobby     = 7 
     interventionism   = 5 
    }
	peacetime_ic_mod       = 0.3 #
   headofstate            = {  type = 9 id = 5001  } 
   headofgovernment       = {  type = 9 id = 5002  } 
   foreignminister        = {  type = 9 id = 5003  } 
   armamentminister       = {  type = 9 id = 5004  } 
   ministerofsecurity     = {  type = 9 id = 5005  } 
   ministerofintelligence = {  type = 9 id = 5006  } 
   chiefofstaff           = {  type = 9 id = 5007  } 
   chiefofarmy            = {  type = 9 id = 5008  } 
   chiefofnavy            = {  type = 9 id = 5009  } 
   chiefofair             = {  type = 9 id = 5010  } 
   # #################
   # ###FRENCH OOB####
   # #################
   landunit = 
   {  id       = {  type = 13500 id = 1  } 
     name     = "Garnison de Paris" 
     location = 55 
     leader   = 5144 #Weygand
     Division = 
     {  id    = {  type = 13500 id = 2  } 
       name  = "1ème Division d'Infanterie" 
       type  = infantry 
	   model = 7
      } 
     Division = 
     {  id   = {  type = 13500 id = 3  } 
       name = "2ème Division d'Infanterie" 
       type = infantry 
	   model = 6
      } 
      Division = 
     {  id       = {  type = 13500 id = 5  } 
       name     = "1ème Division de Cavalerie" 
       type     = cavalry 
       model    = 7 
      } 
    }

    landunit = 
   {  id       = {  type = 13500 id = 6  } 
     name     = "Garnison de Lyon" 
     location = 85 
     Division = 
     {  id    = {  type = 13500 id = 7  } 
       name  = "3ème Division d'Infanterie" 
       strength = 20
       type  = infantry 
       model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 8  } 
       name  = "5ème Division d'Infanterie"
       strength = 20 
       type  = infantry 
        model = 5
      } 
    }

   landunit = 
   {  id       = {  type = 13500 id = 9  } 
     name     = "Police Coloniale d'Alger" 
     location = 727 
     Division = 
     {  id    = {  type = 13500 id = 10  } 
       name  = "1ère Division Police Coloniale" 
       strength = 20
       type  = militia 
	   model = 4
     extra = police
       model = 1
      } 
     Division = 
     {  id    = {  type = 13500 id = 11  } 
       name  = "2ème Division Police Coloniale"
       strength = 20 
       type  = militia 
	   model = 4
     extra = police
       model = 1
      } 
     Division = 
     {  id    = {  type = 13500 id = 12  } 
       name  = "3ème Division Police Coloniale" 
       strength = 20
       type  = militia 
	     model = 4
       extra = police
       model = 1
      } 
    } 

     landunit = 
   {  id       = {  type = 13500 id = 13  } 
     name     = "Police Coloniale de Dakar" 
     location = 978 
     Division = 
     {  id    = {  type = 13500 id = 14  } 
       name  = "4ème Division Police Coloniale" 
       strength = 20
       type  = militia 
     model = 4
     extra = police
       model = 1
      } 
     Division = 
     {  id    = {  type = 13500 id = 15  } 
       name  = "5ème Division Police Coloniale"
       strength = 20 
       type  = militia 
     model = 4
     extra = police
       model = 1
      } 
     Division = 
     {  id    = {  type = 13500 id = 16  } 
       name  = "6ème Division Police Coloniale" 
       strength = 20
       type  = militia 
       model = 4
       extra = police
       model = 1
      } 
    } 

   landunit = 
   {  id       = {  type = 13500 id = 17  } 
     name     = "Garnison de Caen" 
     location = 44 
     leader   = 5746 #Petain
     Division = 
     {  id    = {  type = 13500 id = 18  } 
       name  = "6ème Division d'Infanterie" 
       strength = 40
       type  = infantry 
       model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 19  } 
       name  = "7ème Division d'Infanterie"
       strength = 20 
       type  = infantry 
        model = 5
      } 
    }

   landunit = 
   {  id       = {  type = 13500 id = 20  } 
     name     = "Garnison Bordelaise" 
     location = 68 
     Division = 
     {  id   = {  type = 13500 id = 21  } 
       name = "Garnison Bordelaise"
       strength = 50 
       type = garrison 
	   model = 3
      }
      Division =
     {  id   = {  type = 13500 id = 22  } 
       name = "Garnison Bordelaise"
       strength = 50 
       type = garrison 
     model = 3
      }
    }

    landunit = 
   {  id       = {  type = 13500 id = 23  } 
     name     = "Garnison de Nice" 
     location = 87
     Division = 
     {  id    = {  type = 13500 id = 24  } 
       name  = "8ème Division d'Infanterie" 
       strength = 20
       type  = infantry 
       model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 25  } 
       name  = "9ème Division d'Infanterie"
       strength = 20 
       type  = infantry 
        model = 5
      } 
    }

    landunit = 
   {  id       = {  type = 13500 id = 26  } 
     name     = "Garnison de Marseille" 
     location = 89
     Division = 
     {  id    = {  type = 13500 id = 27  } 
       name  = "10ème Division d'Infanterie" 
       strength = 20
       type  = infantry 
       model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 28  } 
       name  = "11ème Division d'Infanterie"
       strength = 20 
       type  = infantry 
        model = 5
      } 
    }

    landunit = 
   {  id       = {  type = 13500 id = 29  } 
     name     = "Garnison de Brest" 
     location = 37
     Division = 
     {  id    = {  type = 13500 id = 30  } 
       name  = "12ème Division d'Infanterie" 
       strength = 20
       type  = infantry 
       model = 6
      } 
     Division = 
     {  id    = {  type = 13500 id = 31  } 
       name  = "13ème Division d'Infanterie"
       strength = 20 
       type  = infantry 
        model = 5
      } 
    }

	# ############
	# French Navy
	# ############
	navalunit = { 
		id = { type = 13500 id = 118 } 
		name = "1ère Flotte" 
		location = 37 
		base = 37 
		division = { 
			id = { type = 13500 id = 119 } 
			name = "Béarn" 
			type = escort_carrier 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 120 } 
			name = "1ère Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 121 } 
			name = "Lorraine" 
			type = battleship 
			model = 3 
			extra1 = naval_anti_air_l
			extra2 = floatplane
			brigade_model2 = 4
			} 
    division = { 
      id = { type = 13500 id = 132 } 
      name = "Courbet" 
      type = battleship 
      model = 2 
      } 
		division = { 
			id = { type = 13500 id = 126 } 
			name = "Primauguet" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 127 } 
			name = "Duguay-Trouin" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 129 } 
			name = "Lamotte-Picquet" 
			type = light_cruiser 
			model = 3 
			} 
		} 

	navalunit = { 
		id = { type = 13500 id = 130 } 
		name = "2ème Flotte" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 133 } 
			name = "Paris" 
			type = battleship 
			model = 2 
			} 
		division = { 
			id = { type = 13500 id = 135 } 
			name = "Duquesne" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 136 } 
			name = "Pluton" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 137 } 
			name = "Jeanne d'Arc" 
			type = light_cruiser 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 139 } 
			name = "2ème Flottille de Contre-Torpilleurs" 
			type = destroyer
			model = 5
			} 
		division = { 
			id = { type = 13500 id = 138 } 
			name = "3ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		}

	navalunit = { 
		id = { type = 13500 id = 140 } 
		name = "3ème Flotte" 
		location = 728 
		base = 728 
		division = { 
			id = { type = 13500 id = 144 } 
			name = "Tourville" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 145 } 
			name = "4ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 146 } 
			name = "5ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4 
			} 
		} 

	navalunit = { 
		id = { type = 13500 id = 149 } 
		name = "1ère Flotte de Sous-marins" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 150 } 
			name = "Surcouf" 
			type = nuclear_submarine 
			model = 0 
			extra1 = floatplane
			brigade_model1 = 4
			} 
		division = { 
			id = { type = 13500 id = 151 } 
			name = "1ère Flottille de Sous-Marins" 
			type = submarine 
			model = 3
			} 
		division = { 
			id = { type = 13500 id = 152 } 
			name = "2ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 153 } 
			name = "3ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		} 

	navalunit = { 
		id = { type = 13500 id = 160 } 
		name = "3ème Flotte de Sous-marins" 
		location = 727 
		base = 727 
		division = { 
			id = { type = 13500 id = 161 } 
			name = "9ème Flottille de Sous-Marins" 
			type = submarine 
			model = 3 
			} 
		division = { 
			id = { type = 13500 id = 162 } 
			name = "10ème Flottille de Sous-Marins" 
			type = submarine 
			model = 2
			} 
		division = { 
			id = { type = 13500 id = 163 } 
			name = "11ème Flottille de Sous-Marins" 
			type = submarine 
			model = 2 
			} 
		} 
	navalunit = { 
		id = { type = 13500 id = 167 } 
		name = "Transport Expéditionnaire" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 168 } 
			name = "1ère Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 169 } 
			name = "2ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 170 } 
			name = "3ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 171 } 
			name = "8ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 4
			}
		}
	navalunit = {
		id = { type = 13500 id = 174 } 
		name = "Transport Général" 
		location = 86 
		base = 86 
		division = { 
			id = { type = 13500 id = 175 } 
			name = "4ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 176 } 
			name = "7ème Flottille de Convoi" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13500 id = 177 } 
			name = "11ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 4
			} 
		division = { 
			id = { type = 13500 id = 178 } 
			name = "12ème Flottille de Contre-torpilleurs" 
			type = destroyer 
			model = 4
			} 
		}

	navalunit = { 
		id = { type = 13500 id = 184 } 
		name = "2e Flotte de la France" 
		location = 37 
		base = 37 
		division = { 
			id = { type = 13500 id = 185 } 
			name = "15ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 0
			} 
		division = { 
			id = { type = 13500 id = 286 } 
			name = "16ème Flottille de Contre-Torpilleurs" 
			type = destroyer 
			model = 0
			} 
		}
	# ###############
	# French Airforce
	# ###############
   airunit = 
   {  id       = {  type = 13500 id = 188  } 
     name     = "1ère Groupe de Bombardement" 
     location = 55 
     base     = 55 
     Division = 
     {  id       = {  type = 13500 id = 189  } 
       name     = "Groupe de Bombardement Tactique 1" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
     Division = 
     {  id       = {  type = 13500 id = 190  } 
       name     = "Groupe de Bombardement Tactique 2" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
    }
   airunit = 
   {  location = 89 
     base     = 89 
     id       = {  type = 13500 id = 294  } 
     name     = "5ème Groupe de Bombardement" 
     Division = 
     {  id       = {  type = 13500 id = 295  } 
       name     = "Groupe de Bombardement Tactique 7" 
       strength = 100 
       type     = tactical_bomber 
	   model = 4
      } 
    }
   airunit = 
   {  location = 55 
     base     = 55 
     id       = {  type = 13500 id = 196  } 
     name     = "1er Groupe de Chasse" 
     Division = 
     {  id       = {  type = 13500 id = 197  } 
       name     = "Groupe de Chasse 24" 
       strength = 100 
       type     = interceptor 
       model    = 7
      } 
     Division = 
     {  id       = {  type = 13500 id = 198  } 
       name     = "Groupe de Chasse 21" 
       strength = 100 
       type     = interceptor 
       model    = 7 
      } 
    }
   airunit = 
   {  location = 65 
     base     = 65 
     id       = {  type = 13500 id = 199  } 
     name     = "3ème Groupe de Chasse" 
     Division = 
     {  id       = {  type = 13500 id = 200  } 
       name     = "Groupe de Chasse 23" 
       strength = 100 
       type     = interceptor 
	   model = 7
      } 
    }
airunit = 
   {  id       = {  type = 13500 id = 201  } 
     name     = "6ère Groupe de Bombardement" 
     location = 43
     base     = 43
     Division = 
     {  id       = {  type = 13500 id = 202  } 
       name     = "Groupe de Bombardement Tactique 3" 
       strength = 100 
       type     = tactical_bomber 
     model = 4
      } 
    }



   # ################################# 
   # Naval units under construction 
   # ################################# 
   #france is shid lol they cant build ships

}
 
