 
 ############################## 
 # Country definition for GER # 
 ############################## 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = GER 
	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes } }
	capital                = 163 
	manpower               = 0
	transports             = 600 
	escorts                = 80

	# Resource Reserves 
	energy                 = 9000
	metal                  = 4500
	rare_materials         = 2250
	oil                    = 15000 
	supplies               = 3000
	money                  = 300 
   diplomacy = 
   {  relation = {  tag = ARG value = 75  } 
     relation = {  tag = AST value = 1  } 
     relation = 
     {  tag        = AUS 
       value      = 100 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = BEL value = 20  } 
     relation = {  tag = BHU value = 1  } 
     relation = {  tag = BOL value = 15  } 
     relation = {  tag = BRA value = 50  } 
     relation = 
     {  tag        = BUL 
       value      = 25 
       #guaranteed = {  day = 29 month = december year = 1935  } 
      } 
     relation = {  tag = CAN value = 1  } 
     relation = {  tag = CHL value = 50  } 
     relation = {  tag = COL value = -20  } 
     relation = 
     {  tag        = CZE 
       value      = -25 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = ENG value = 1  } 
     relation = 
     {  tag        = DEN 
       value      = 25 
       guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = EST value = 10  } 
     relation = 
     {  tag        = FIN 
       value      = 25 
       #guaranteed = {  day = 22 month = august year = 1934  } 
      } 
     relation = {  tag = FRA value = -35  } 
     relation = {  tag = GRE value = 15  } 
     relation = {  tag = HOL value = 1  } 
     relation = {  tag = HUN value = 100  } 
     relation = {  tag = IRE value = 15  } 
     relation = {  tag = IRQ value = 25  } 
     relation = 
     {  tag        = ITA 
       value      = -50#50 
       guaranteed = {  day = 29 month = december year = 1935  } 
      } 
     relation = {  tag = JAP value = 20  } 
     relation = {  tag = LAT value = 10  } 
     relation = {  tag = LIT value = -50  } 
     relation = {  tag = LUX value = -50  } 
     relation = {  tag = MAN value = 20  } 
     relation = {  tag = NEP value = 1  } 
     relation = {  tag = NZL value = 1  } 
     relation = {  tag = OMN value = 1  } 
     relation = 
     {  tag        = POL 
       value      = -10 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
     relation = {  tag = POR value = 75  } 
     relation = 
     {  tag        = ROM 
       value      = 50 
       #guaranteed = {  day = 29 month = december year = 1935  } 
      } 
     relation = {  tag = SAF value = 1  } 
     relation = 
     {  tag        = SCH 
       value      = 50 
       guaranteed = {  day = 16 month = may year = 1935  } 
      } 
     relation = {  tag = SOV value = 1  } 
     relation = {  tag = SPR value = -50  } 
     relation = 
     {  tag        = SWE 
       value      = 50 
       #guaranteed = {  day = 29 month = december year = 1935  } 
      } 
     relation = 
     {  tag        = TUR 
       value      = 100 
       #guaranteed = {  day = 29 month = december year = 1935  } 
      } 
     relation = {  tag = USA value = -10  } 
     relation = {  tag = YEM value = 1  } 
     relation = 
     {  tag        = YUG 
       value      = 50 
       #guaranteed = {  day = 29 month = december year = 1932  } 
      } 
    } 
   SpyInfo                = {  country = "GER" NumberOfSpies = 7  } 
   
   nationalprovinces      = {  104 105 107 109 110 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 216 221 222 224 225 226 261 
                             } 
   ownedprovinces         = {  104 105 107 109 110 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 216 221 222 224 225 226 261 
   ###COLONIES
   846 847 894 897 898 899 901 902 903 904 905 906 #Congo
   846 847 848 849 850 851 852 #Tanganyika
   893 907 908 909 910 911 912 913 914 915 916 917 918 919 920 923 924 925 926 927 928 #France, Portugal, Spain, Cameroon
   882 883 884 885 886 #Namibia
   948 949 950 951 955 #Togo
   834 835 836 837 838 815 816 817 833 #East Africa
   1001 1002 1003 996 999 1000 #Madagascar
   1752 1767 1768 2000 #West Indies
   1234 1587 1602 1603 1604 1605 1610 1725 1726 1727 1731 1730 1740 1743 1744 1581 1582 1583 1584 1585 1586 1772 # Pacific
   1391 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 #Indochina
                             } 
   controlledprovinces    = {  104 105 107 109 110 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 216 221 222 224 225 226 261 
   ###COLONIES
   # AFRICA
   846 847 894 897 898 899 901 902 903 904 905 906 #From Belgium
   846 847 848 849 850 851 852 #Tanganyika
   893 907 908 909 910 911 912 913 914 915 916 917 918 919 920 923 924 925 926 927 928 #France, Portugal, Spain, Cameroon
   882 883 884 885 886 #Namibia
   948 949 950 951 955 #Togo
   834 835 836 837 838 815 816 817 833 #East Africa
   1001 1002 1003 996 999 1000 #Madagascar
   1752 1767 1768 2000 #West Indies
   1234 1587 1602 1603 1604 1605 1610 1725 1726 1727 1731 1730 1740 1743 1744 1581 1582 1583 1584 1585 1586 1772 # Pacific 
   1391 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 #Indochina
                             } 
claimedprovinces = { 
   # AFRICA
   846 847 894 897 898 899 901 902 903 904 905 906 #From Belgium
   846 847 848 849 850 851 852 #Tanganyika
   893 907 908 909 910 911 912 913 914 915 916 917 918 919 920 923 924 925 926 927 928 #France, Portugal, Spain, Cameroon
   882 883 884 885 886 #Namibia
   948 949 950 551 955 #Togo
   834 835 836 837 838 815 816 817 833 #East Africa
   1001 1002 1003 996 999 1000 #Madagascar 1730 1740 1743 1744
   1752 1767 1768 #West Indies
   1234 1587 1602 1603 1605 1610 1665 1666 1667 1668 1669 1670 1671 1674 1675 1676 1677 1681 1684 1685 1686 1725 1726 1727 1730 1740 1743 1744 1581 1582 1583 1584 1585 1586 # Pacific
   1731 #Apia
   1328 # Qingdao
}
	# Germany 1936 techs 
	####################### 
	techapps = { 
	#Early Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090
	#SEMI-MOTORIZED CAVALRY 
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 
	# Motorized Infantry
	1396
	#Early Mountain Division 
	1160  1170 1180 1190 1200 1210 1220 1230 1240
	#Engineers
	1830 1840 1850 1860
	#Interbellum 1930 Supply
	1910 1920 1930 1940 1950 1960 1970 1980

	#Basic Armoured Car  
	2860 2870 2880 2020 2150
	#Early Tank 
	7600 7610 2620 2010 2630 2640 2646 2650 2030
	#Early Field Artillery 
	2290 2300 2310 2900 2910 2920 2930
	#Early Static Anti-Air Artillery 
	2800 2450 21180 21190 21200
	#Basic Anti-Air Artillery Brigade 
	2810 2820 2510

	#Improved Destroyer 
	3010 3020 3030 3040 3050 3060
	#Basic Light Cruiser 
	3110 3120 3130 3140 3150 3160
	#Improved Heavy Cruiser 
	3210 3220 3230 3240 3250 3260  
	#Early Battlecruiser
	3310 3320 3330 3340
	#Early Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470
	#Improved Submarine 
	3610 3620 3630 3640 3650
	#Great War Air Carrier 
	3510
	#CAG
	4900
	#Improved Light carrier 
	12100 12110
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3900
	#Troopships
	3810 3820

	#Basic Air Transport 
	4290 4250
	#Multirole fighter
	4300 4310 4320 4330 4340
	#CAS
	4400
	#ww1 strategic bomber
	4800 4810 4820
	#ww1 navalbomber
	4700 4710
	#Early Fighter  
	4500 4510 4520 4530 4540 4550 4010 4020
	#Early Bomber
	4600 4610 4620 4630 4120 4130
	#SEAPLANES
	4740 4750 4760

	#Manufacturing
	5810 5820 5050 5830 5060
	#Improved Construction Engineering 
	5800 5080 5090
	#Basic Oil Refining
	5190 5200
	#Computers & cryptografi
	5310 54010 54020 54030 5316 5326
	#Exp. Rocket
	5560
	#Mechanized Agriculture 
	5700 5710 5010 5020
	#Medicine
	5600 5610 5620 5630

	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6610 6680 6690 6700 6710 6910
	# WW2 Land Doctrines
	6210 6220 6230 6250 6900
	#Great War Hospital System 
	14000 14010 14020

	#Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9090

	#Naval Doctrines
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300
	# Naval Logistics
	82500
	# Naval Interdiction
	8500 8510 8520 8550 8560 8570
	# Trade Interdiction Submarine
	8600 8610
	# Indirect Approach
	81300 81310 81320 81330 81340 81350
	# Naval Supremacy
	8100 8110 8120 8150 8160 8170 8200 8210
	# rocket test facilities
	7550
}
 
inventions = { 3000027 3000028 }
blueprints = { 6240 6260 6270 7560 } # Elastic Defense, Combined Arms Off. and Kampfgruppe doctrines
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 7
     political_left    = 3 
     free_market       = 7
     freedom           = 7                                              
     professional_army = 4 
     defense_lobby     = 6 
     interventionism   = 7 
    } 
	peacetime_ic_mod       = 0.4
   headofstate            = {  type = 9 id = 1  } 
   headofgovernment       = {  type = 9 id = 2  } 
   foreignminister        = {  type = 9 id = 3  } 
   armamentminister       = {  type = 9 id = 4  } 
   ministerofsecurity     = {  type = 9 id = 5  } 
   ministerofintelligence = {  type = 9 id = 6  } 
   chiefofstaff           = {  type = 9 id = 7  } 
   chiefofarmy            = {  type = 9 id = 8  } 
   chiefofnavy            = {  type = 9 id = 9  } 
   chiefofair             = {  type = 9 id = 10  } 
   dormant_leaders        = {  36 44 54 66 67 223 226 292 352 473 479 526
							   542 543 544 546 547 549 550 551 553 558 559 560 561 562 563 
							   567 571 572 573 578 595 686 712 746 749 816 821 909 983 992
							   576 1007 1008 #Vlassov Zverev Budyho
							}
							
   


   ###GENERAL STAFF & INSPECTORATES
   landunit = 
   {  location = 163 
      leader   = 604
      locked = yes
     name     = "Grosser Generalstab" 
     id       = {  type = 14500 id = 1  } 
     Division = 
     {  id       = {  type = 14500 id = 2  } 
       name     = "Deutches Generalstab" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
     Division = 
     {  id       = {  type = 14500 id = 3  } 
       name     = "Generalstab-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    } 

    landunit = 
   {  location = 181 
     name     = "I. Armee Inspektion" 
     id       = {  type = 14500 id = 4  } 
     Division = 
     {  id       = {  type = 14500 id = 5  } 
       name     = "I. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 6  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    } 
    landunit = 
   {  location = 163 
     name     = "II. Armee Inspektion" 
     id       = {  type = 14500 id = 7  } 
     Division = 
     {  id       = {  type = 14500 id = 8  } 
       name     = "II. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 9  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
    landunit = 
   {  location = 146 
     name     = "III. Armee Inspektion" 
     id       = {  type = 14500 id = 10  } 
     Division = 
     {  id       = {  type = 14500 id = 11  } 
       name     = "II. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 12  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
    landunit = 
   {  location = 179 
     name     = "IV. Armee Inspektion" 
     id       = {  type = 14500 id = 13  } 
     Division = 
     {  id       = {  type = 14500 id = 14  } 
       name     = "IV. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 15  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
    landunit = 
   {  location = 136 
     name     = "V. Armee Inspektion" 
     id       = {  type = 14500 id = 16  } 
     Division = 
     {  id       = {  type = 14500 id = 17  } 
       name     = "V. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 18  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
    landunit = 
   {  location = 134 
     name     = "VI. Armee Inspektion" 
     id       = {  type = 14500 id = 19  } 
     Division = 
     {  id       = {  type = 14500 id = 20  } 
       name     = "VI. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 21  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
    landunit = 
   {  location = 224 
     name     = "VII. Armee Inspektion" 
     id       = {  type = 14500 id = 22  } 
     Division = 
     {  id       = {  type = 14500 id = 23  } 
       name     = "VII. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 24  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
    landunit = 
   {  location = 127 
     name     = "VIII. Armee Inspektion" 
     id       = {  type = 14500 id = 25  } 
     Division = 
     {  id       = {  type = 14500 id = 26  } 
       name     = "VIII. Armee Inspektion" 
       type     = hq 
       model    = 2
       strength = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 27  } 
       name     = "Inspektorat-Garnison" 
       type     = garrison 
       model    = 4 
       strength = 90 
      } 
    }
##########ARMEEKORPS

####1. INSPECTORATE

landunit = 
   {  location = 182 
     name     = "I. Armeekorps" 
     id       = {  type = 14500 id = 101  } 
     Division = 
     {  id       = {  type = 14500 id = 102  } 
       name     = "1. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 103  } 
       name          = "11. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 104  } 
       name     = "21. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 
landunit = 
   {  location = 222 
     name     = "II. Armeekorps" 
     id       = {  type = 14500 id = 105  } 
     Division = 
     {  id       = {  type = 14500 id = 106  } 
       name     = "2. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 107  } 
       name          = "12. Infanterie-Division" 
       type          = infantry 
       model         = 9
       extra         = heavy_armor
       brigade_model = 0
       strength      = 100 
      } 
     Division = 
     {  id       = {  type = 14500 id = 108  } 
       name     = "22. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 109 } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = cavalry_brigade 
       brigade_model = 9
       strength      = 100 
      } 
} 
landunit = 
   {  location = 185 
     name     = "XVII. Armeekorps" 
     id       = {  type = 14500 id = 110  } 
     Division = 
     {  id       = {  type = 14500 id = 111  } 
       name     = "41. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 112  } 
       name          = "32. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 113  } 
       name     = "29. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

####2. INSPECTORATE

landunit = 
   {  location = 163 
     name     = "Garde-Korps" 
     id       = {  type = 14500 id = 114  } 
     Division = 
     {  id            = {  type = 14500 id = 115  } 
       name          = "Garde-Kavalerie-Division " 
       type          = infantry 
       model         = 8
       extra         = cavalry_brigade 
       brigade_model = 9
       strength      = 100 
      } 
     Division = 
     {  id       = {  type = 14500 id = 116  } 
       name     = "1. Garde-Infanterie-Division" 
       type     = infantry 
       model    = 9
       strength = 100 
       extra         = artillery 
       brigade_model = 7
       strength      = 100 
      } 
      Division = 
     {  id       = {  type = 14500 id = 117  } 
       name     = "2. Garde-Infanterie-Division" 
       type     = infantry 
       model    = 9
       strength = 100 
      } 
} 
landunit = 
   {  location = 173 
     name     = "XII. Armeekorps" 
     id       = {  type = 14500 id = 118  } 
     Division = 
     {  id       = {  type = 14500 id = 119  } 
       name     = "23. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 120  } 
       name     = "32. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 121  } 
       name     = "5. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 
landunit = 
   {  location = 172 
     name     = "XIX. Armeekorps" 
     id       = {  type = 14500 id = 122  } 
     Division = 
     {  id       = {  type = 14500 id = 123  } 
       name     = "26. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 124  } 
       name          = "28. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 125  } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 


####3. INSPECTORATE

landunit = 
   {  location = 152 
     name     = "IX. Armeekorps" 
     id       = {  type = 14500 id = 126  } 
     Division = 
     {  id       = {  type = 14500 id = 127  } 
       name     = "10. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 128  } 
       name     = "29. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 129  } 
       name     = "40. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 
landunit = 
   {  location = 146 
     name     = "X. Armeekorps" 
     id       = {  type = 14500 id = 130  } 
     Division = 
     {  id       = {  type = 14500 id = 131  } 
       name     = "19. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90
       extra         = cavalry_brigade 
       brigade_model = 9
       strength      = 100  
      } 
     Division = 
     {  id            = {  type = 14500 id = 132  } 
       name          = "20. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 133  } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

landunit = 
   {  location = 141 
     name     = "VII. Armeekorps" 
     id       = {  type = 14500 id = 134  } 
     Division = 
     {  id       = {  type = 14500 id = 135  } 
       name     = "25. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 136  } 
       name          = "33. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 137  } 
       name     = "26. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 


####4. INSPECTORATE

landunit = 
   {  location = 178 
     name     = "I. Bayerisches Armee-Korps" 
     id       = {  type = 14500 id = 138  } 
     Division = 
     {  id       = {  type = 14500 id = 139  } 
       name     = "1. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 140  } 
       name     = "2. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 141  } 
       name     = "3. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 
landunit = 
   {  location = 176 
     name     = "II. Bayerisches Armee-Korps" 
     id       = {  type = 14500 id = 142  } 
     Division = 
     {  id       = {  type = 14500 id = 143  } 
       name     = "4. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 144  } 
       name          = "1. Bayerische-Kavalerie-Division" 
       type          = cavalry 
       model         = 9
       extra         = engineer 
       brigade_model = 3
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 145  } 
       name     = "5. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

landunit = 
   {  location = 175 
     name     = "III. Bayerisches Armee-Korps" 
     id       = {  type = 14500 id = 146  } 
     Division = 
     {  id       = {  type = 14500 id = 147  } 
       name     = "6. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 148  } 
       name          = "7. Bayerische-Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 149  } 
       name     = "8. Bayerische-Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 


####5. INSPECTORATE

landunit = 
   {  location = 129 
     name     = "VIII. Armeekorps" 
     id       = {  type = 14500 id = 200  } 
     Division = 
     {  id       = {  type = 14500 id = 201  } 
       name     = "15. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 202  } 
       name     = "16. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 203  } 
       name     = "17. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = cavalry_brigade 
       brigade_model = 9
       strength      = 100 
      } 
} 
landunit = 
   {  location = 136 
     name     = "XIV. Armeekorps" 
     id       = {  type = 14500 id = 204  } 
     Division = 
     {  id       = {  type = 14500 id = 205  } 
       name     = "36. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 206  } 
       name          = "38. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 207  } 
       name     = "17. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

landunit = 
   {  location = 107 
     name     = "XV. Armeekorps" 
     id       = {  type = 14500 id = 208  } 
     Division = 
     {  id       = {  type = 14500 id = 209  } 
       name     = "50. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 210  } 
       name          = "48. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 211  } 
       name     = "46. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 


####6. INSPECTORATE

landunit = 
   {  location = 169 
     name     = "IV. Armeekorps" 
     id       = {  type = 14500 id = 212  } 
     Division = 
     {  id       = {  type = 14500 id = 213  } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 214  } 
       name     = "14. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 215  } 
       name     = "37. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = cavalry_brigade 
       brigade_model = 9
       strength      = 100 
      } 
} 
landunit = 
   {  location = 137 
     name     = "XI. Armeekorps" 
     id       = {  type = 14500 id = 216  } 
     Division = 
     {  id       = {  type = 14500 id = 217  } 
       name     = "24. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 218  } 
       name          = "52. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 219  } 
       name     = "51. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

landunit = 
   {  location = 134 
     name     = "XIII. Armeekorps" 
     id       = {  type = 14500 id = 220  } 
     Division = 
     {  id       = {  type = 14500 id = 221  } 
       name     = "13. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 222  } 
       name          = "43. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 223  } 
       name     = "42. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

####7. INSPECTORATE

landunit = 
   {  location = 166 
     name     = "XVI. Armeekorps" 
     id       = {  type = 14500 id = 224  } 
     Division = 
     {  id       = {  type = 14500 id = 225  } 
       name     = "54. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 226  } 
       name     = "55. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 227  } 
       name     = "33. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 
landunit = 
   {  location = 221 
     name     = "XVIII. Armeekorps" 
     id       = {  type = 14500 id = 228  } 
     Division = 
     {  id       = {  type = 14500 id = 229  } 
       name     = "53. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 230  } 
       name          = "44. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 231  } 
       name     = "7. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

landunit = 
   {  location = 224 
     name     = "XXI. Armeekorps" 
     id       = {  type = 14500 id = 232  } 
     Division = 
     {  id       = {  type = 14500 id = 233  } 
       name     = "59. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 234  } 
       name          = "16. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 235  } 
       name     = "19. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 


####8. INSPECTORATE

landunit = 
   {  location = 104 
     name     = "II. Armeekorps" 
     id       = {  type = 14500 id = 236  } 
     Division = 
     {  id       = {  type = 14500 id = 237  } 
       name     = "60. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 238  } 
       name     = "63. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
      Division = 
     {  id       = {  type = 14500 id = 239  } 
       name     = "68. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90
       extra         = cavalry_brigade 
       brigade_model = 9
       strength      = 100  
      } 
} 
landunit = 
   {  location = 138 
     name     = "V. Armeekorps" 
     id       = {  type = 14500 id = 240  } 
     Division = 
     {  id       = {  type = 14500 id = 241  } 
       name     = "62. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 242  } 
       name          = "63. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 243  } 
       name     = "55. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 

landunit = 
   {  location = 107 
     name     = "VI. Armeekorps" 
     id       = {  type = 14500 id = 245  } 
     Division = 
     {  id       = {  type = 14500 id = 246  } 
       name     = "69. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 100
       extra         = heavy_armor
       brigade_model = 0
       strength      = 100  
      } 
     Division = 
     {  id            = {  type = 14500 id = 247  } 
       name          = "4. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 248  } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
} 


#MARINE

   navalunit = 
   {  name     = "Hochseeflotte" 
     id       = {  type = 14500 id = 500  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 501  } 
       name  = "SMS SMS Baden" 
       type  = battleship 
       model = 5
      } 
     Division = 
     {  id    = {  type = 14500 id = 502  } 
       name  = "SMS Bayern" 
       type  = battleship 
       model = 5
      } 
      Division = 
     {  id    = {  type = 14500 id = 503  } 
       name  = "SMS Friedrich der Grosse" 
       type  = battleship 
       model = 4
      } 
      Division = 
     {  id    = {  type = 14500 id = 504  } 
       name  = "SMS Grosser Kurfurst" 
       type  = battleship 
       model = 4
      } 
      Division = 
     {  id    = {  type = 14500 id = 506  } 
       name  = "SMS Kaiser" 
       type  = battleship 
       model = 4
      } 
       Division = 
      {  id    = {  type = 14500 id = 507  } 
       name  = "SMS Kaiserin" 
       type  = battleship 
       model = 4
      } 
       Division = 
      {  id    = {  type = 14500 id = 508  } 
       name  = "SMS Konig" 
       type  = battleship 
       model = 5
      } 
       Division = 
      {  id    = {  type = 14500 id = 509  } 
       name  = "SMS Konig Albert" 
       type  = battleship 
       model = 5
      }
        
       Division = 
      {  id    = {  type = 14500 id = 511  } 
       name  = "SMS Markgraf" 
       type  = battleship 
       model = 5
      } 
       Division = 
      {  id    = {  type = 14500 id = 512  } 
       name  = "SMS Prinzregent Luitpold" 
       type  = battleship 
       model = 4
      } 
       Division = 
     {  id    = {  type = 14500 id = 513  } 
       name  = "SMS Kaiser Wilhelm" 
       type  = battleship 
       model = 6
      } 
       Division = 
      {  id    = {  type = 14500 id = 514  } 
       name  = "SMS Preussen" 
       type  = battleship 
       model = 6
      } 
            Division = 
     {  id    = {  type = 14500 id = 522  } 
       name  = "SMS Wurttemberg" 
       type  = battleship 
       model = 5
      } 
     Division = 
     {  id    = {  type = 14500 id = 523  } 
       name  = "SMS Sachsen" 
       type  = battleship 
       model = 5
      } 
     Division = 
     {  id    = {  type = 14500 id = 524  } 
       name  = "SMS Moltke" 
       type  = battlecruiser
       model = 0
      } Division = 
      {  id    = {  type = 14500 id = 525  } 
       name  = "SMS Seydlitz" 
       type  = battlecruiser
       model = 1
      } Division = 
      {  id    = {  type = 14500 id = 526  } 
       name  = "SMS Derfflinger" 
       type  = battlecruiser
       model = 1
      } Division = 
      {  id    = {  type = 14500 id = 527  } 
       name  = "SMS Lutzow" 
       type  = battlecruiser
       model = 1
      } Division = 
      {  id    = {  type = 14500 id = 528  } 
       name  = "SMS Hindenburg" 
       type  = battlecruiser
       model = 1
      }  Division = 
      {  id    = {  type = 14500 id = 531  } 
       name  = "SMS Prinz Eitel Friedrich" 
       type  = battlecruiser
       model = 1
      } Division = 
      {  id    = {  type = 14500 id = 532  } 
       name  = "SMS Furst Bismarck" 
       type  = battlecruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 533  } 
       name  = "SMS Ersatz Yorck" 
       type  = battlecruiser
       model = 2
      }
       Division = 
      {  id    = {  type = 14500 id = 534  } 
       name  = "SMS Ersatz Gniesenau" 
       type  = battlecruiser
       model = 2
      }
       Division = 
      {  id    = {  type = 14500 id = 536  } 
       name  = "SMS Hipper" 
       type  = battlecruiser
       model = 2
      } 
      Division = 
      {  id    = {  type = 14500 id = 537  } 
       name  = "SMS Blucher" 
       type  = heavy_cruiser
       model = 3
      }
       Division = 
      {  id    = {  type = 14500 id = 538  } 
       name  = "SMS Gazelle" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 539  } 
       name  = "SMS Niobe" 
       type  = light_cruiser
       model = 1
      } 
      Division = 
     {  id    = {  type = 14500 id = 546  } 
       name  = "3. Zerstorergeschwader" 
       type  = destroyer 
       model = 3
      } 
     Division = 
     {  id    = {  type = 14500 id = 547  } 
       name  = "4. Zerstorergeschwader" 
       type  = destroyer 
       model = 3 
      } 
      Division = 
     {  id    = {  type = 14500 id = 548  } 
       name  = "5. Zerstorergeschwader" 
       type  = destroyer 
       model = 3
      } 
      Division = 
     {  id    = {  type = 14500 id = 549  } 
       name  = "7. Zerstorergeschwader" 
       type  = destroyer 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 550  } 
       name  = "8. Zerstorergeschwader" 
       type  = destroyer 
       model = 4 
      } 
    } 
      

 navalunit = 
   {  name     = "Atlantischflotte" 
     id       = {  type = 14500 id = 599  } 
     location = 915
     base     = 915
     Division =  
      {  id    = {  type = 14500 id = 510  } 
       name  = "SMS Kronprinz Wilhelm" 
       type  = battleship 
       model = 5
      }
     Division = 
      {  id    = {  type = 14500 id = 529  } 
       name  = "SMS Mackensen" 
       type  = battlecruiser
       model = 1
      } Division = 
      {  id    = {  type = 14500 id = 530  } 
       name  = "SMS Graf Spee" 
       type  = battlecruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 540  } 
       name  = "SMS Nymphe" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 541  } 
       name  = "SMS Thetis" 
       type  = light_cruiser
       model = 1
      } 
       Division = 
      {  id    = {  type = 14500 id = 542  } 
       name  = "SMS Ariadne" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 543  } 
       name  = "SMS Amazone" 
       type  = light_cruiser
       model = 1
      } 
      Division = 
     {  id    = {  type = 14500 id = 544  } 
       name  = "1. Zerstorergeschwader" 
       type  = destroyer 
       model = 0
      } 
     Division = 
     {  id    = {  type = 14500 id = 545  } 
       name  = "2. Zerstorergeschwader" 
       type  = destroyer 
       model = 0 
      } 
     Division = 
      {  id    = {  type = 14500 id = 535  } 
       name  = "SMS Ersatz Scharnhorst" 
       type  = battlecruiser
       model = 2
      }
}






 navalunit = 
   {  name     = "Ostasiengeschwader" 
     id       = {  type = 14500 id = 551  } 
     location = 1602
     base     = 1602
     Division = 
      {  id    = {  type = 14500 id = 552  } 
       name  = "SMS Scheer" 
       type  = heavy_cruiser
       model = 3
      }
       Division = 
      {  id    = {  type = 14500 id = 553  } 
       name  = "SMS Schmidt" 
       type  = heavy_cruiser
       model = 3
      }  
      Division = 
      {  id    = {  type = 14500 id = 554  } 
       name  = "SMS Maass" 
       type  = heavy_cruiser
       model = 3
      }
       Division = 
      {  id    = {  type = 14500 id = 555  } 
       name  = "SMS Qingdao" 
       type  = carrier
       model = 0
       extra = cag
       brigade_model = 0
      }
       Division = 
      {  id    = {  type = 14500 id = 556  } 
       name  = "SMS Frauenlob" 
       type  = light_cruiser
       model = 1
      } 
       Division = 
      {  id    = {  type = 14500 id = 557  } 
       name  = "SMS Arcona" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 558  } 
       name  = "SMS Undine" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 559  } 
       name  = "SMS Stuttgart" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 560  } 
       name  = "SMS Stettin" 
       type  = light_cruiser
       model = 1
      } 
       Division = 
      {  id    = {  type = 14500 id = 561  } 
       name  = "SMS Kolberg" 
       type  = light_cruiser
       model = 1
      }
       Division = 
      {  id    = {  type = 14500 id = 562  } 
       name  = "SMS Augsburg" 
       type  = light_cruiser
       model = 1
      }
      Division = 
      {  id    = {  type = 14500 id = 563  } 
       name  = "SMS Stralsund" 
       type  = light_cruiser
       model = 1
      }
      Division = 
      {  id    = {  type = 14500 id = 564  } 
       name  = "SMS Wiesbaden" 
       type  = light_cruiser
       model = 2
      } 
       Division = 
      {  id    = {  type = 14500 id = 565  } 
       name  = "SMS Magdeburg" 
       type  = light_cruiser
       model = 2
      }
       Division = 
      {  id    = {  type = 14500 id = 566  } 
       name  = "SMS Leipzig" 
       type  = light_cruiser
       model = 2
      }
      Division = 
      {  id    = {  type = 14500 id = 567  } 
       name  = "SMS Frauenlob" 
       type  = light_cruiser
       model = 2
      }
      Division = 
     {  id    = {  type = 14500 id = 568  } 
       name  = "9. Zerstorergeschwader" 
       type  = destroyer 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 569  } 
       name  = "10. Zerstorergeschwader" 
       type  = destroyer 
       model = 4 
      } 
      Division = 
     {  id    = {  type = 14500 id = 570  } 
       name  = "11. Zerstorergeschwader" 
       type  = destroyer 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 571  } 
       name  = "12. Zerstorergeschwader" 
       type  = destroyer 
       model = 4 
      } 
}



     
 navalunit = 
   {  name     = "I. Truppentransporter Flotte" 
     id       = {  type = 14500 id = 3104  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 3105  } 
       name  = "1. Truppentransporterflottille" 
       type = transport
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 3106  } 
       name  = "2. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 3107  } 
       name  = "3. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
    } 
   navalunit = 
   {  name     = "II. Unterseebootsflotte" 
     id       = {  type = 14500 id = 320  } 
     location = 152 
     base     = 152 
     Division = 
     {  id    = {  type = 14500 id = 321  } 
       name  = "2. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 325  } 
       name  = "3. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
    } 
   navalunit = 
   {  name     = "I. Unterseebootsflotte" 
     id       = {  type = 14500 id = 326  } 
     location = 147 
     base     = 147 
     Division = 
     {  id    = {  type = 14500 id = 327  } 
       name  = "1. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 3200 } 
       name  = "4. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
    } 
   navalunit = 
   {  name     = "Baltische Flotte" 
     id       = {  type = 14500 id = 328  } 
     location = 184 
     base     = 184 
           Division = 
      {  id    = {  type = 14500 id = 515  } 
       name  = "Wilhelmshaven" 
       type  = battleship 
       model = 6
      } 
      Division = 
      {  id    = {  type = 14500 id = 516  } 
       name  = "Nassau" 
       type  = battleship 
       model = 3
      }
      Division = 
      {  id    = {  type = 14500 id = 517  } 
       name  = "Westfalen" 
       type  = battleship 
       model = 4
      }
      Division = 
      {  id    = {  type = 14500 id = 518  } 
       name  = "Helgoland" 
       type  = battleship 
       model = 4
      }
      Division = 
      {  id    = {  type = 14500 id = 519  } 
       name  = "Ostfrieseland" 
       type  = battleship 
       model = 4
      }
      Division = 
      {  id    = {  type = 14500 id = 520  } 
       name  = "Thuringen" 
       type  = battleship 
       model = 4
      }
      Division = 
      {  id    = {  type = 14500 id = 521  } 
       name  = "Oldenburg" 
       type  = battleship 
       model = 4
      }
     Division = 
     {  id    = {  type = 14500 id = 331  } 
       name  = "13. Zerstorergeschwader" 
       type  = destroyer 
       model = 3
      } 
     Division = 
     {  id    = {  type = 14500 id = 332  } 
       name  = "14. Zerstorergeschwader" 
       type  = destroyer 
       model = 2
      } 
     Division = 
     {  id    = {  type = 14500 id = 3155 } 
       name  = "15. Zerstorergeschwader" 
       type  = destroyer 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 3156  } 
       name  = "16. Zerstorergeschwader" 
       type  = destroyer 
       model = 0
      } 
    } 
   # ######### Luftwaffe ############## 
   airunit = 
   {  location = 163 
     id       = {  type = 14500 id = 486  } 
     name     = "Luftflotte II" 
     base     = 163 
     Division = 
     {  id       = {  type = 14500 id = 487  } 
       name     = "KG 2 'Holzhammer'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 488  } 
       name     = "KG 3 'Blitz'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 489  } 
       name     = "Sturzkampfgeschwader 51" 
       strength = 100 
       type     = CAS 
       model    = 0
      } 
     Division = 
     {  id            = {  type = 14500 id = 490  } 
       name          = "JG 2 'Richthofen'" 
       strength      = 100 
       type          = interceptor 
       model         = 7
      } 
     Division = 
     {  id            = {  type = 14500 id = 491  } 
       name          = "JG 26 'Schlageter'" 
       strength      = 100 
       type          = interceptor 
       model         = 7
      } 
     Division = 
     {  id            = {  type = 14500 id = 492  } 
       name          = "Kampfgeschwader zbV 172 'Hindenburg'" 
       strength      = 50 
       type          = transport_plane 
       model         = 1
      } 
    } 
   airunit = 
   {  location = 167 
     id       = {  type = 14500 id = 495  } 
     name     = "Luftflotte III" 
     base     = 167 
     Division = 
     {  id       = {  type = 14500 id = 496  } 
       name     = "KG 53 'Legion Condor'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 497  } 
       name     = "Kampfgeschwader 25" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 498  } 
       name     = "KG 30 'Adler'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
    } 
   airunit = 
   {  location = 137 
     id       = {  type = 14500 id = 499  } 
     name     = "Luftflotte IV" 
     base     = 137 
     Division = 
     {  id       = {  type = 14500 id = 4100  } 
       name     = "KG 1 'Hindenburg'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 4101  } 
       name     = "JG 3 'Udet'" 
       strength = 100 
       type     = interceptor 
       model    = 7
      } 
    } 
   airunit = 
   {  location = 179 
     id       = {  type = 14500 id = 4102  } 
     name     = "Luftflotte V" 
     base     = 179 
     Division = 
     {  id       = {  type = 14500 id = 4103  } 
       name     = "KG 4 'General Wever'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
    }

airunit = 
   {  location = 142 
     id       = {  type = 14500 id = 4104  } 
     name     = "Luftflotte V" 
     base     = 142 
     Division = 
     {  id            = {  type = 14500 id = 4105  } 
       name          = "JG 19 'M. Richthofen'" 
       strength      = 100 
       type          = multi_role 
       model         = 3
      } 
     Division = 
     {  id            = {  type = 14500 id = 4106  } 
       name          = "JG 11 'Reinhard'" 
       strength      = 100 
       type          = multi_role 
       model         = 3
      } 
      Division = 
     {  id            = {  type = 14500 id = 4107  } 
       name          = "JG 12 'L. Richthofen'" 
       strength      = 100 
       type          = multi_role 
       model         = 3
      } 
     Division = 
     {  id            = {  type = 14500 id = 4108  } 
       name          = "JG 26 'Goering'" 
       strength      = 100 
       type          = multi_role 
       model         = 4
      } 
    }





}
	