 
 ######################################### 
 # Country definition for Wallonia (U17) # 
 #########################################
 ## Made by Markush ##
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = U17 
	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes } }
	capital                = 108 
	manpower               = 5 
	# Resource Reserves 
	energy                 = 2040
	metal                  = 1020
	rare_materials         = 510
	oil                    = 500 
	supplies               = 500 
	money                  = 20 
	transports             = 100 
	escorts                = 20 
	
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 6 
     political_left    = 3 
     free_market       = 4 
     freedom           = 6 
     professional_army = 9 
     defense_lobby     = 9
     interventionism   = 1 
    } 	
	
	
   diplomacy = 
   {  
     relation = {  tag = GER value = 200 access = yes }  
    } 
   SpyInfo                = {  country = "U17" NumberOfSpies = 6  } 
   nationalprovinces      = {  108 111 112 113  } 
   ownedprovinces         = {  108 111 112 113  } 
   controlledprovinces    = {  108 111 112 113  } 
   # Western Minor Tech '36 
   # Group C 1936 techs 
   # ###################### 
   techapps               = { 
#Early Infantry Division  
1010  1020 1030 1040 1050 1060 1070 1080 1090
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Motorised Inf
1396
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960 1970 1980
#1930 Cavalry Division  
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
#Engineers
1830 1840 1850 1860

#Basic Armoured Car  
2860 2870 2880 2020
#Tankette 
7600 7610 2620 2010 2630 2640
#Great War Heavy Field Artillery 
2290 2300 2310 
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510

# Destroyers 
3010
#Torpedo & ASW 18
3720 3730 3900
#Troopships
3810

#Early Fighter  
4500 4510 4520 4530 4540 4550 4010 4020
#Interwar Bomber 
4600 4610 4620 4630 4120

#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Medicine
5600 5610 5620 5630
#Modern Agriculture 
5700 5710 5010
#Manufactoring
5810 5820 5050 5830 5060
#Improved Construction Engineering 
5800 5080 5090

#Great War Hospital System 
14000 14010 14020
# Great War Land Doctrines
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
# Defensive Focus Grand Battleplan Path (FRA / UK)
6560 6030 6110
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 
}
inventions = { 3000027 } 

   headofstate            = {  type = 9 id = 70001  } 
   headofgovernment       = {  type = 9 id = 70002  } 
   foreignminister        = {  type = 9 id = 70003  } 
   armamentminister       = {  type = 9 id = 70004  } 
   ministerofsecurity     = {  type = 9 id = 70005  } 
   ministerofintelligence = {  type = 9 id = 70213  } #Robert de Foy
   chiefofstaff           = {  type = 9 id = 70007  } 
   chiefofarmy            = {  type = 9 id = 70008  } 
   chiefofnavy            = {  type = 9 id = 70009  } 
   chiefofair             = {  type = 9 id = 70010  } 
}
